### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by Yo-yo-ooo** [marceldobehere/MaslOS#12]
After burning, I found it stopped at line 177 of KernelUnitl.cpp when running

**Comment by Yo-yo-ooo** [comment]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/98507772/224312611-cfd0f693-a0a0-4f38-9d01-cb919d2d591e.png">

**Comment by marceldobehere** [comment]
Is it still broken for you?

**Comment by Yo-yo-ooo** [comment]
![微信图片_20230311114423](https://user-images.githubusercontent.com/98507772/224463238-9f5f4f2a-9d30-450e-b959-3241be8ee116.jpg)

**Comment by Yo-yo-ooo** [comment]
stopped there.

**Comment by marceldobehere** [comment]
Thats a weird place to freeze. 
It might be because of the Memory Mapping of the framebuffer at line 187. 

I'll probably add a detailed verbose bootscreen today so it should show the last action it takes before freezing.

But if it is because of the framebuffer then I would be very confused and concerned. #

I would try comme

**Comment by marceldobehere** [comment]
Okay.
I have added a verbose boot (enabled by default)
Also I have remove some code with the Framebuffer.

You can see if it works now.

**Comment by Yo-yo-ooo** [comment]
Thanks!

**Comment by marceldobehere** [comment]
Were you able to boot successfully?

**Comment by Yo-yo-ooo** [comment]
Yes

**Comment by Yo-yo-ooo** [comment]
Thank you.
















At 2023-03-12 14:24:09, "Masl" ***@***.***> wrote:

Were you able to boot successfully?

**Comment by marceldobehere** [comment]
No worries! Is it working well for you?
